FROM maven:3.9.4-eclipse-temurin-21

RUN apt-get update -y && apt-get install -y unzip curl

ENV BASE_URL=https://otus.ru
ENV BROWSER=chrome
# ENV URL=http://127.0.0.1/wd/hub
ENV ALLURE_VERSION=2.34.1

WORKDIR /tests

COPY . /tests

RUN mvn clean install -DskipTests

RUN curl -L -o /tmp/allure.zip https://github.com/allure-framework/allure2/releases/download/${ALLURE_VERSION}/allure-${ALLURE_VERSION}.zip \
    && unzip /tmp/allure.zip -d /opt/ \
    && rm /tmp/allure.zip \
    && ln -s /opt/allure-${ALLURE_VERSION}/bin/allure /usr/bin/allure

RUN mkdir -p /tests/allure-results /tests/allure-report

CMD mvn clean test \
      -Dbrowser=${BROWSER} \
      -DbaseUrl=${BASE_URL} \
      # -Durl=${URL} \
      -Djava.awt.headless=false \
      -Dsurefire.ignoreFailures=true \
      -Dallure.results.directory=/tests/allure-results \
    && allure generate /tests/allure-results -o /tests/allure-report --clean